language: julia

notifications:
  email: false

julia:
  - 1.0
  - 1.2
  - 1.3
  - nightly

matrix:
  fast_finish: true
  allow_failures:
    - julia: nightly

after_success:
  - |
      julia -e '
          using Pkg
          Pkg.add("Coverage")
          using Coverage
          Coveralls.submit(Coveralls.process_folder())
          Codecov.submit(process_folder())
      '
